# Generated by Django 3.0.3 on 2020-02-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20)),
                ('fechanac', models.DateField()),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('fechaingreso', models.DateField()),
                ('puesto', models.CharField(max_length=50)),
                ('salario', models.IntegerField()),
            ],
        ),
    ]
